<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\Applications\" />
    <Folder Include="Repositories\Interfaces\" />
    <Folder Include="Repositories\Implementations\" />
    <Folder Include="Services\Interfaces\" />
    <Folder Include="Services\Implementations\" />
  </ItemGroup>

</Project>
